[package]
name = "vesper-agent"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
futures-util.workspace = true
glob.workspace = true
regex.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
vesper-domain = { path = "../vesper-domain", version = "=0.3.0" }
vesper-provider = { path = "../vesper-provider", version = "=0.3.0" }
vesper-runtime = { path = "../vesper-runtime", version = "=0.3.0" }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
vesper-testkit = { path = "../vesper-testkit", version = "=0.3.0" }

[lints]
workspace = true
